//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTiana
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int id_client { get; set; }
        public int inn { get; set; }
        public int kpp { get; set; }
        public int r_s { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string NameOrganization { get; set; }
    }
}
