//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTiana
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public int id_salary { get; set; }
        public int Salary1 { get; set; }
        public int id_worker { get; set; }
        public int Prize { get; set; }
    
        public virtual Workers Workers { get; set; }
    }
}
