//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTiana
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workers
    {
        public int id_worker { get; set; }
        public string FIO { get; set; }
        public string Phone { get; set; }
        public string Position { get; set; }
        public string Email { get; set; }
        public int SeriasPasport { get; set; }
        public int NumberPasport { get; set; }
    }
}
